rules_dictionary = {"[]": "means a set of characters. ",
              "\\": "means signals a special sequence (can also be used to escape special characters). ",
              ".": "means any character (except newline character). ",
              "^": "means starts with. ",
              "$": "means ends with. ",
              "*": "means zero or more occurrences. ",
              "+": "means one or more occurrences. ",
              "?": "means zero or one occurrences. ",
              "{}": "means exactly the specified number of occurrences. ",
              "|": "means either or. ",
              "()": "means capture and group. ",
              "\A": "returns a match if the specified characters are at the beginning of the string. ",
              "\\b": "returns a match where the specified characters are at the beginning or at the end of a word. ",
              "\B": "returns a match where the specified characters are present, but NOT at the beginning (or at the end) of a word. ",
              "\d": "returns a match where the string contains digits (numbers from 0-9). ",
              "\D": "returns a match where the string DOES NOT contain digits. ",
              "\s": "returns a match where the string contains a white space character. ",
              "\S": "returns a match where the string DOES NOT contain a white space character. ",
              "\w": "returns a match where the string contains any word characters. ",
              "\W": "returns a match where the string DOES NOT contain any word characters. ",
              "\Z": "returns a match if the specified characters are at the end of the string. "}

set_dictionary = {"[arn]": "returns a match where one of the specified characters (a, r, or n) are present. ",
                  "[a-n]": "returns a match for any lower case character, alphabetically between a and n. ",
                  "[^arn]": "returns a match for any character EXCEPT a, r, and n. ",
                  "[0123]": "returns a match where any of the specified digits (0, 1, 2, or 3) are present. ",
                  "[0-9]": "returns a match for any digit between 0 and 9. ",
                  "[0-5][0-9]": "returns a match for any two-digit numbers from 00 and 59. ",
                  "[a-zA-Z]": "returns a match for any character alphabetically between a and z, lower case OR upper case. ",
                  "[+]": "in sets, +, *, ., |, (), $,{} has no special meaning, so [+] means: return a match for any + character in the string. ",}

