# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Nos\PycharmProjects\pythonProject\rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Rules(object):
    def setupUi(self, Rules):
        Rules.setObjectName("Rules")
        Rules.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(Rules)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(140, 10, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(48)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 80, 581, 371))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        Rules.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Rules)
        self.statusbar.setObjectName("statusbar")
        Rules.setStatusBar(self.statusbar)

        self.retranslateUi(Rules)
        QtCore.QMetaObject.connectSlotsByName(Rules)

    def retranslateUi(self, Rules):
        _translate = QtCore.QCoreApplication.translate
        Rules.setWindowTitle(_translate("Rules", "Rules"))
        self.name.setText(_translate("Rules", "ReGex Rules"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Rules = QtWidgets.QMainWindow()
    ui = Ui_Rules()
    ui.setupUi(Rules)
    Rules.show()
    sys.exit(app.exec_())
